### ISSUE TITLE
How do you see your highlights/notes/bookmarks in a list?

### ISSUE THREAD

**Issue by Cindy-Jie-01** [LinusCDE/plato#5]

**Comment by LinusCDE** [comment]
Hi. Sorry for the late response, apparently one does not watch a fork by default, so I was never notified.

I just looked it up. Seems to be available from the "reader menu". The reader menu is viewed when clicking on the book title that is part of the top bar in the reader. There you got "Annotations" (highlights and notes) and "Bookmarks".

**Comment by Kratacoa** [comment]
> I just looked it up. Seems to be available from the "reader menu". The reader menu is viewed when clicking on the book title that is part of the top bar in the reader. There you got "Annotations" (highlights and notes) and "Bookmarks".

I don't have any of that; the document I've checked is a PDF, and the version installed is the one packaged by `toltec`. [Here is a screnshot](https://i.imgur.com/xjnmyNN.png).

**Comment by ozel** [comment]
it's not the menu on the right. you have to tap on the name of the document in the centre on the top.
When _no_ annotations and bookmarks are defined, only zoom mode and dithering options are shown in that menu.

**Comment by Kratacoa** [comment]
> it's not the menu on the right. you have to tap on the name of the document in the centre on the top.
> When _no_ annotations and bookmarks are defined, only zoom mode and dithering options are shown in that menu.

Oh yes, sorry, I chose the wrong screenshot. Anyway, I only see the "zoom" option, when clicking on the name of the document.  I have both an annotation and a bookmark in the file, as described by [manual in the doc folder](https://github.com/LinusCDE/plato/blob/master/doc/MANUAL.md).

**Comment by ozel** [comment]
hm strange, in my case it works quite well in the latest version V0.9.13, with epubs and PDFs. have you tried it with different files? 
I have not yet tried viewing annotations and bookmarks that were not created in plato, by the way.

**Comment by Kratacoa** [comment]
I had V0.9.1, upgrading did the trick. Cheers.

**Comment by LinusCDE** [comment]
> I had V0.9.1, upgrading did the trick. Cheers.
> EDIT: However, I'm having an unrelated issue right now, that is bookmarks and annotations not being saved. Is it as intended, and they are not supposed to be persistent?

I'm not sure either. Maybe because plato only safes some things (at least settings) when properly quit and not killed?
@baskerville, do you now anything more specific on this?

**Comment by baskerville** [comment]
The current library won't be flushed if *Plato* is killed.

**Comment by Kratacoa** [comment]
Seems that was it. Thank you for your assistance (and your code) :)
