### ISSUE TITLE
Table of Contents not displaying in normal mode

### ISSUE THREAD

**Issue by sternj** [LinusCDE/plato#6]
Tapping the southwest corner doesn't display anything in normal mode, though all other corners do. Running Plato `0.9.13-1` on a remarkable 2 running firmware 2.5.0.27

**Comment by LinusCDE** [comment]
Tested it out and can't reproduce it. Tapped the corner in an epub and it got displayed. Does your file have a table of contents (or plato support it for that fileformat)?

Maybe knowing the file format and whether it has a toc on a PC or elsewhere would help.

**Comment by sternj** [comment]
Interesting.... it was a document that I converted to epub v3 from v2 in Calibre. Tapping the left corner in its original v2 version brought me back to the contents page, but it didn't do that in the v3 for some reason. I'll close this issue if you don't have any more digging to do, I think it may be an issue in the upstream
