### ISSUE TITLE
Settings.toml/plato.toml not parsed

### ISSUE THREAD

**Issue by ozel** [LinusCDE/plato#7]
While trying to get the [article_fetcher](https://github.com/baskerville/plato/blob/master/doc/ARTICLE_FETCHER.md) hook working, I noticed that this fork of plato cannot read its own main settings file, linked from /opt/etc/plato.toml:
```
reMarkable: ~/ rm2fb-client plato     
Can't load settings: Cannot parse TOML content from Settings.toml.
```
Tested with the V0.9.13 release, shipped via toltec/entware.
Is it maybe related to this fix 4e720aae7f3e9e588f62317a179f522a6aa8cdf0 which came just after the package release? I haven't built this repo myself, yet.

It regularly even overwrites the settings file with defaults which made it very confusing to debug the article_fetcher hook. Is that a fallback feature of rust? 
According to original plato docs, the main settings file should be only edited when plato is in 'shared mode', but I guess that is specific to Kobo readers. I also tried editing the settings file while plato was not running with the same behaviour.

This is probably unrelated, but could there be another issue with network access from this plato fork on the rm2? After putting the hook's setting file in the correct default place (`/opt/lib/plato/bin/article_fetcher/` and not `~/bin/...` as one could assume) the article_fetcher reports at least "Establishing a network connection." and sometimes "Waiting for the network to come up." but always returns with nothing. 

Thanks for this port, btw, I really like Plato on the RM2!

**Comment by LinusCDE** [comment]
I honestly didn't use the article fetcher yet, so I have next-to-no knowledge on that. If the assumed location is indeed wrong, I would definitely need to fix that for the reMarkable as well.

The commit you mentioned was an unrelated issue if I'm not mistaken. Read https://github.com/LinusCDE/plato/commit/76344f5ffcba6d915c25bea9ad4b9110b06eca88#r45951005 . I made this change because saving the file failed, but this was caused because I forgot to ensure that structs are at the bottom in the Settings struct that defines the toml file (new changes put primitive types below it and I didn't know the exact problem). I reverted it in the commit you mentioned to work as intended, but I don't think that releasing a new version with that commit has any urgency.

Maybe the article fetcher attempts to save the toml file somewhere else? That could explain the fail. Also not sure why loading is affected.

To be certain I made an impromptu recreation of the ipkg file for the newest commit. Can you confirm the same error with [this one](https://github.com/LinusCDE/plato/files/5894750/plato_0.9.13-1_armv7-3.2.ipk.zip)?

**Comment by baskerville** [comment]
> This is probably unrelated, but could there be another issue with network access from this plato fork on the rm2? After putting the hook's setting file in the correct default place (`/opt/lib/plato/bin/article_fetcher/` and not `~/bin/...` as one could assume) the article_fetcher reports at least "Establishing a network connection." and sometimes "Waiting for the network to come up." but always returns with nothing.

What happens is that the fetcher is waiting for an event (of type *network*) that it never receives. As mentioned in `doc/HOOKS.md`, this event is sent to all the fetchers when the network becomes available. To do so, *Plato* relies on `Event::Device(DeviceEvent::NetUp)`. This event is generated when the related message is read from `/tmp/nickel-hardware-status`, a FIFO created by `/etc/init.d/rcS`. This message is written by `/etc/udhcpc.d/default.script`.

**Comment by LinusCDE** [comment]
Thanks for the heads up! I'll look at the existing code and probably patch in a simple replacement for it then (which would likely just check for a default route or iwconfig).

**Comment by ozel** [comment]
> To be certain I made an impromptu recreation of the ipkg file for the newest commit. Can you confirm the same error with [this one](https://github.com/LinusCDE/plato/files/5894750/plato_0.9.13-1_armv7-3.2.ipk.zip)?

Thanks! Unfortunately, it did not change anything. But could it be also related to how I am calling Plato from the command line in order to see the output? 
Anyway, the main behaviour is unchanged, if I edit settings in `/opt/etc/plato.toml` they get reset to defaults after Plato is started from the oxide launcher once _closed_ again.
Is Settings.toml expected to exist somewhere in /etc? I thought I've previously seen a link from there to /opt/lib/plato/ but it seems gone now.

Regarding the article fetcher, I found out the binary runs just fine (with its own local setting file configured) when started from the CLI with a folder and two times "true" as arguments. I tried to find out where those arguments are passed on to hooks in the main Plato code, but without luck so far.

If one of you cloud point me to more documentation about the Media & Library menus (yes, I've seen the doc folder) on the lover left that would be highly appreciated. For example, how to add a sub-folder? And there is often this mention about [two modes](https://github.com/baskerville/plato/blob/master/doc/LIBRARY.md), what are they exactly and is this relevant on an rM device? (c.f. my remarks about the 'shared mode' in my initial post, could be really related to this issue as well)

**Comment by LinusCDE** [comment]
Hi,

sorry for this late response. I think the fix I made did at least fix the parsing (even if it was not best fix to the problem I caused in this fork). If I'm mistaken and the most recent release/toltec-package doesn't work, I should really make a new release asap.

I think the two modes refer to how directories are handled (or how deep). As far as I can remember when I tested it a lot, "filesystem mode" was truer to displaying subdirectories where as "database mode" considers the files more the be a flattened list. I think folders are just treated as tags in both versions (which I'm personally not a fan of, but my usecase was not the typical ereader one).

My personal preference was to have one library entry for each subfolder to not get different mangas mixed up. I switched those from the context menu in the lower left of the home screen.

I think you can just test both modes by changing the type of a "[[library]]" (or similar) entry in the Settings.toml and probably also purging all metadata in that folder. (In toml, all "[[<name here>]]" entries basically turn into a list of whatever name was in the double brackets. So you can duplicate that entry as often as you like.)

**Comment by LinusCDE** [comment]
The newest update should use the old system again. If the error pops up again, feel free to reopen this.

**Comment by Albatrosicks** [comment]
I managed to fix the **article_fetcher**.

A few words about the configuration:
-  plato launches **article_fetcher** in the working directory, which is `/opt/lib/plato`
  - This means the **article_fetcher** settings are stored in `/opt/lib/plato/Settings.toml` (this could cause an issue with the config being overwritten)
  - `external-urls-queue` is specified as `external-urls-queue=urls.txt`
  - For hooks, we create a link to the directory we need:
  ```bash
  mkdir -p /home/root/plato-media/Articles
  ln -s /home/root/plato-media/Articles Articles
  ```

There's some kind of Wi-Fi issue in the plato fork, possibly only on my reMarkable 2. To avoid figuring out the cause of the Wi-Fi problems, I'm running wifi separately in the background and launching the hook. And to prevent the hook from throwing an error, I removed this if code block: https://github.com/LinusCDE/plato/blob/1e3311041e3b2cb793e6220e37a32dc5ebf93184/crates/fetcher/src/main.rs#L137-L158
I built **article_fetcher** with:
```bash
cargo build --profile release-minsized -Z build-std=std,panic_abort \
                     --target armv7-unknown-linux-gnueabihf \
                     --bin article_fetcher -p fetcher
```

Alternatively, I added the following paths in `creates/fetcher/src/main.rs`:
```rust
const SETTINGS_PATH: &str = "bin/article_fetcher/Settings.toml";
const SESSION_PATH: &str = "bin/article_fetcher/.session.json";
const URLS_PATH: &str = "bin/article_fetcher/urls.txt";
```
Then `external-urls-queue` is specified as `external-urls-queue=bin/article_fetcher/urls.txt`

**UPD.** I'm looking into the wifi issue, and I'm thinking of checking "/home/root/log.txt" for the following line ([here](https://github.com/LinusCDE/plato/blob/master/crates/core/src/input.rs#L374)):

```
Feb 02 03:49:31.190 Info: wlan0: Link is up (:0, )
```

Also here are my draft of `/opt/lib/plato/scripts` for reMarkable (fw v. 3.3.2.1666):

<details>
  <summary><b>essid.sh</b></summary>

```bash
#! /bin/sh

wpa_cli -i wlan0 status | grep "^ssid=" | cut -d= -f2
```

</details>

<details>
  <summary><b>ip.sh</b></summary>

```bash
#! /bin/sh

ip -4 addr show wlan0 | grep -oE 'inet [0-9.]+' | cut -d' ' -f2
```

</details>

<details>
  <summary><b>wifi-enable.sh</b> - here, I think I can add a line to "/home/root/log.txt" about the Wi-Fi being brought up.</summary>

```bash
#! /bin/sh

INTERFACE=wlan0
SOURCE_CONF="/home/root/.config/remarkable/wifi_networks.conf"
TEMP_CONF="/tmp/plato_wifi.conf"

if [ -f "$SOURCE_CONF" ]; then
    sed -e '/ieee80211w=/d' \
        -e 's/WPA-PSK WPA-PSK-SHA256/WPA-PSK/g' \
        "$SOURCE_CONF" > "$TEMP_CONF"
else
    echo "ctrl_interface=/var/run/wpa_supplicant" > "$TEMP_CONF"
    echo "update_config=1" >> "$TEMP_CONF"
fi

if ! grep -q "^brcmfmac " "/proc/modules"; then
    modprobe brcmfmac
    sleep 1
fi

if systemctl is-active -q wpa_supplicant; then
    systemctl stop wpa_supplicant
fi

if pidof wpa_supplicant > /dev/null; then
    killall wpa_supplicant
    sleep 1
fi

ifconfig "$INTERFACE" up

wpa_supplicant -B -i "$INTERFACE" -c "$TEMP_CONF" -C /var/run/wpa_supplicant

if ! systemctl is-active -q dhcpcd; then
    systemctl start dhcpcd
fi

# here we could change to adding line to /home/root/log.txt
echo "network bound" > "/tmp/nickel-hardware-status"

SCRIPTS_DIR=$(dirname "$0")
POST_UP_SCRIPT=$SCRIPTS_DIR/wifi-post-up.sh
[ -e "$POST_UP_SCRIPT" ] && $POST_UP_SCRIPT
```
</details>

<details>
  <summary><b>wifi-disable.sh</b></summary>

```bash
#!/bin/sh

if systemctl is-active -q wpa_supplicant; then
    systemctl stop wpa_supplicant
fi

if pidof wpa_supplicant; then
    wpa_cli terminate
fi

if ! systemctl is-enabled -q dhcpcd; then
    systemctl stop dhcpcd
fi

ifconfig wlan0 down

if grep -q "^brcmfmac " "/proc/modules"; then
    modprobe -r brcmfmac
fi
```

</details>
