### ISSUE TITLE
RTL (manga) support

### ISSUE THREAD

**Issue by bensleveritt** [LinusCDE/plato#9]
I know this is more an upstream thing, but I wondered if Plato had RTL support. In the manga-sense. I can't tell how different this port is to upstream, but I'm quietly confident that @LinusCDE reads manga...

**Comment by LinusCDE** [comment]
This would be indeed a nice thing to implement. I have indeed read a manga series of about 200 volumes on plato and pondered on the idea myself. I mostly got used to just having the buttons (on the rm1) reversed to the reading flow.

For the buttons at least, i think you can reverse them by selecting the "natural something" option. I'm currently pretty occupied with lots of university/college projects (not sure how it translates to the american system) and also quite some work to do. I think the change should be quite doable in theory, but would add another changed quirk of this port to the upstream version. I would personally have it being rather similar to the original one with only some rM specific tweaks. Should I find the time to do those changes, I would most likely try to get them upstream anyway.

I currently plan to have more free time starting end of summer. Maybe I'll get another manga-craze then and add this feature, but for now I'll have to pass on the feature. 

(I also wanted to add [Mango](https://github.com/hkalexling/Mango) support (or just plain [opds](https://en.wikipedia.org/wiki/Open_Publication_Distribution_System) which mango offers) to have some kind of easy synching. But I guess this branch never got beyond [a hello world app draft](https://github.com/LinusCDE/plato/tree/feature/mango-app) and a pretty basic and mostly naively designed [rust lib](https://crates.io/crates/mango-client) to extract the data from the server.)

This is also probably of interest to @baskerville .

**Comment by bensleveritt** [comment]
Thanks for the reply. And I think you're right, this is an upstream request really. I'll open up there and hopefully we'll see it trickle down to rmPlato!

**Comment by bensleveritt** [comment]
Had a mild realisation that you could just swap the button handlers for RTL documents, which could be easier than true RTL support...
